#!/bin/bash

# =============================================================================
# Enhanced Zsh + Plugins + Git Prompt Setup Script (Optimized)
# Supports Debian/Ubuntu, RHEL/CentOS/Fedora, Arch Linux, and openSUSE systems
# =============================================================================

set -euo pipefail  # Exit on error, undefined vars, pipe failures

# === CONSTANTS ===
readonly SCRIPT_VERSION="2.0"
readonly ZSH_PLUGIN_DIR="${HOME}/.zsh/plugins"
readonly ZSHRC="${HOME}/.zshrc"
readonly PLUGIN_REPOS=(
    "https://github.com/zsh-users/zsh-autosuggestions"
    "https://github.com/zsh-users/zsh-syntax-highlighting.git"
)

# === COLOR FUNCTIONS ===
info() {
    echo -e "\n\033[1;32m==> $1\033[0m"
}

warn() {
    echo -e "\n\033[1;33m==> ⚠️  $1\033[0m"
}

error() {
    echo -e "\n\033[1;31m==> ❌ ERROR: $1\033[0m" >&2
}

success() {
    echo -e "\033[1;32m✅ $1\033[0m"
}

# === PACKAGE MANAGEMENT ===
detect_pkg_manager() {
    if command -v apt-get &>/dev/null; then
        echo "apt"
    elif command -v dnf &>/dev/null; then
        echo "dnf"
    elif command -v yum &>/dev/null; then
        echo "yum"
    elif command -v zypper &>/dev/null; then
        echo "zypper"
    elif command -v pacman &>/dev/null; then
        echo "pacman"
    else
        error "Could not detect package manager"
        return 1
    fi
}

install_packages() {
    local pkg_manager="$1"
    shift
    local packages=("$@")

    info "Installing packages: ${packages[*]}"

    case "$pkg_manager" in
        apt)
            sudo apt-get update && sudo apt-get install -y "${packages[@]}"
            ;;
        dnf)
            sudo dnf install -y "${packages[@]}"
            ;;
        yum)
            sudo yum install -y "${packages[@]}"
            ;;
        zypper)
            sudo zypper refresh && sudo zypper install -y "${packages[@]}"
            ;;
        pacman)
            sudo pacman -Sy --noconfirm "${packages[@]}"
            ;;
        *)
            error "Unsupported package manager: $pkg_manager"
            return 1
            ;;
    esac
}

# === SYSTEM CHECKS ===
check_sudo() {
    if ! command -v sudo &>/dev/null; then
        error "sudo not found. Please install sudo or run as root."
        return 1
    fi

    if ! sudo -v &>/dev/null; then
        error "Sudo access required. Please run with sudo privileges."
        return 1
    fi
}

check_command() {
    if ! command -v "$1" &>/dev/null; then
        return 1
    fi
    return 0
}

# === SHELL SETUP ===
setup_zsh_shell() {
    local current_shell="$SHELL"
    local zsh_path

    zsh_path="$(command -v zsh)" || {
        error "zsh not found in PATH. Please install zsh first."
        return 1
    }

    if [[ "$current_shell" != *zsh ]]; then
        warn "To set zsh as your default shell, run: chsh -s $zsh_path"
        info "You can also start zsh temporarily by typing 'zsh'"
    else
        success "Zsh is already the default shell"
    fi
}

# === PLUGIN MANAGEMENT ===
install_plugin() {
    local plugin_dir="$1"
    local repo_url="$2"
    local plugin_name="${repo_url##*/}"
    plugin_name="${plugin_name%.git}"

    if [ -d "$plugin_dir/$plugin_name" ]; then
        success "$plugin_name already installed"
        return 0
    fi

    info "Installing $plugin_name..."
    if git clone --depth 1 --quiet "$repo_url" "$plugin_dir/$plugin_name" 2>/dev/null; then
        success "Installed $plugin_name"
        return 0
    else
        warn "Failed to install $plugin_name"
        return 1
    fi
}

# === AUTO-START SETUP ===
setup_auto_start() {
    local shell_rc=""

    case "$SHELL" in
        *bash)
            shell_rc="$HOME/.bashrc"
            ;;
        *zsh)
            shell_rc="$HOME/.zshrc"
            ;;
        *)
            warn "Unknown shell: $SHELL. Cannot setup auto-start."
            return 1
            ;;
    esac

    [ ! -f "$shell_rc" ] && touch "$shell_rc"

    if ! grep -qxF '[ -x "$(command -v zsh)" ] && exec zsh' "$shell_rc"; then
        cat >> "$shell_rc" <<'EOF'

# Auto-start zsh if available
[ -x "$(command -v zsh)" ] && exec zsh
EOF
        success "Added auto-start of zsh to $shell_rc"
    else
        success "Auto-start already configured in $shell_rc"
    fi
}

# === ZSH CONFIGURATION ===
generate_zshrc() {
    # Backup existing zshrc if it exists
    if [ -f "$ZSHRC" ]; then
        local backup="${ZSHRC}.backup.$(date +%Y%m%d_%H%M%S)"
        cp "$ZSHRC" "$backup"
        success "Backed up existing .zshrc to $backup"
    fi

    info "Generating enhanced ~/.zshrc..."

    cat > "$ZSHRC" <<'ZSHRC_EOF'
# =============================================================================
# ENHANCED ZSH CONFIGURATION
# Generated by automated setup script (v2.0)
# =============================================================================

# === PROMPT WITH GIT INTEGRATION ===
autoload -Uz vcs_info
precmd() { vcs_info }
setopt prompt_subst

# Git status styling
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:git:*' stagedstr '✔'
zstyle ':vcs_info:git:*' unstagedstr '✚'
zstyle ':vcs_info:git:*' untrackedstr '?'
zstyle ':vcs_info:git:*' formats ' (%b%u%c)'

# Prompt: user@hostname + current directory + git status
PROMPT='%n@%m %~${vcs_info_msg_0_} > '

# === SHELL OPTIONS ===
setopt auto_cd                    # Change to directory by typing its name
setopt hist_expire_dups_first     # Remove duplicates first when history fills up
setopt hist_ignore_space          # Don't save commands starting with space
setopt hist_verify                # Show history expansion before executing
setopt append_history             # Append to history file
setopt share_history              # Share history between sessions
setopt hist_ignore_all_dups       # Remove old duplicate entries from history

# History configuration
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000

# === AUTOSUGGESTIONS ===
if [ -f "$HOME/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" ]; then
    source "$HOME/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
    ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#999999"
    ZSH_AUTOSUGGEST_STRATEGY=(history completion)
fi

# === SYNTAX HIGHLIGHTING ===
if [ -f "$HOME/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]; then
    source "$HOME/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
    ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)
fi

# === ENVIRONMENT VARIABLES ===
export EDITOR="${EDITOR:-vim}"
export VISUAL="${VISUAL:-$EDITOR}"
export PATH="$HOME/.local/bin:$PATH"

# === ALIASES ===
# File listing
alias ll='ls -lAh'
alias la='ls -A'
alias l='ls -CF'

# Grep with colors
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Safety (interactive mode)
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# === COMPLETION SYSTEM ===
autoload -Uz compinit && compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' rehash true

# === NODE VERSION MANAGER (NVM) ===
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# === LS COLORS ===
if command -v dircolors >/dev/null 2>&1; then
    eval "$(dircolors -b)"
    alias ls='ls --color=auto'
fi
ZSHRC_EOF

    success "Generated enhanced .zshrc configuration"
}

# === MAIN SCRIPT ===
main() {
    info "🚀 Starting Enhanced Zsh Setup (v$SCRIPT_VERSION)..."

    # Detect package manager
    info "Detecting package manager..."
    local pkg_manager
    pkg_manager=$(detect_pkg_manager) || {
        error "Failed to detect package manager"
        return 1
    }
    success "Detected package manager: $pkg_manager"

    # Check sudo access
    info "Checking sudo access..."
    check_sudo || return 1

    # Install required packages
    info "Installing zsh, git, curl, and wget..."
    install_packages "$pkg_manager" zsh git curl wget || {
        error "Failed to install packages"
        return 1
    }

    # Setup shell configuration
    setup_zsh_shell || warn "Failed to set zsh as default shell (non-fatal)"

    # Setup auto-start
    info "Configuring auto-start of zsh..."
    setup_auto_start || warn "Failed to setup auto-start (non-fatal)"

    # Plugin setup
    info "Setting up Zsh plugins..."
    mkdir -p "$ZSH_PLUGIN_DIR"

    local failed_plugins=0
    for repo_url in "${PLUGIN_REPOS[@]}"; do
        install_plugin "$ZSH_PLUGIN_DIR" "$repo_url" || ((failed_plugins++))
    done

    # Generate enhanced .zshrc
    generate_zshrc

    # Completion message
    success "Zsh setup completed successfully!"
    echo
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "🎯 NEXT STEPS:"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "   1. Run 'zsh' to start using Zsh immediately"
    echo "   2. Run 'chsh -s $(command -v zsh)' to make Zsh your default shell"
    echo "   3. Restart your terminal for all changes to take effect"
    echo
    echo "📦 Installed Features:"
    echo "   ✓ Git-aware prompt with username@hostname"
    echo "   ✓ Syntax highlighting"
    echo "   ✓ Autosuggestions"
    echo "   ✓ Enhanced completions"
    echo "   ✓ Useful aliases"
    echo "   ✓ Improved history management"
    echo
    echo "🔧 To customize further, edit: ~/.zshrc"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo

    [ $failed_plugins -gt 0 ] && warn "$failed_plugins plugin(s) failed to install"
}

# Handle script interruption
trap 'error "Script interrupted by user"; exit 130' INT TERM

# Run main function
main "$@"
